- .github/workflows/main.yml
When we publish a release in GitHub the release tag is automatically added to the URL and we do not need this in the binary names. To make downloading the latest binaries easier we are removing the GitHub tag from the asset names.
> refactor(ci): remove git tag from binary names for release assets

- .github/workflows/docker-publish.yml
- .github/workflows/main.yml
- taqueria-plugin-flextesa/docker/Dockerfile
The PR sets up the docker build and publish workflow for a list of plugins in a matrix. This is only needed for the `flextesa` plugin currently
**Test Plan**
Please see the Release section of the repo for listed packages
Please see this PR for the docker comments
Ref #38
> ci(docker): Add workflow to build and publish images

- README.md
- cli.ts
- i18n.ts
- taqueria-config.ts
- taqueria-plugin-flextesa/docker/package-lock.json
- taqueria-plugin-flextesa/index.ts
- taqueria-plugin-flextesa/package-lock.json
- taqueria-plugin-flextesa/proxy.ts
- taqueria-plugin-ligo/compile.js
- taqueria-plugin-ligo/index.js
- taqueria-plugin-ligo/package-lock.json
- taqueria-plugin-mock/package-lock.json
- taqueria-plugin-smartpy/index.ts
- taqueria-plugin-smartpy/package-lock.json
- taqueria-plugin-taquito/index.ts
- taqueria-plugin-taquito/package-lock.json
- taqueria-plugin-teztnets/package-lock.json
- taqueria-protocol/taqueria-protocol-types.ts
- taqueria-sdk/index.ts
- taqueria-sdk/package-lock.json
- taqueria-sdk/package.json
- taqueria-sdk/types.ts
- taqueria-types.ts
- taqueria-utils/taqueria-utils-types.ts
- taqueria-utils/taqueria-utils.ts
This branch fixes #147 but also makes a few other adjustments:
- Adds a task for installing and uninstalling an NPM plugin.  For installation, you can use `taq install @taqueria/plugin-ligo` once the packages are published to npmjs, but `taq install /path/to/taqueria-plugin-ligo` should also work. To uninstall, you must specify the package name - directory paths aren't supported.
- Error messages aren't truncated. This will help with debugging.
- Adds an argument flag for logging plugin requests. When debugging, I often have to uncomment a line in the source of taqueria and re-build. I can then see calls to a plugin logged to the console. I've asked others, like @russellmorton to do this. To make this a little easier, you can now just specify a hidden argument to the taq binary: `taq …
> Fixes #147, tasks not exposed in cli - among other changes

- website/package.json
- website/redirects.txt
This PR adds redirects for the Cloudflare pages site. The redirects will make downloading binaries simpler using friendly URLs.
**Testing Plan**
Please test by downloading the binaries from the following URLs
https://154-chore-redirects-for-webs.taqueria.pages.dev/get/macos/taq
https://154-chore-redirects-for-webs.taqueria.pages.dev/get/linux/taq
https://154-chore-redirects-for-webs.taqueria.pages.dev/get/windows/taq
Once this PR is merged the URLs will work for https://taqueria.io/
Ref #154
> fix(website): add redirects file for binary downloads

- .github/workflows/vscode-extension.yml
@mweichert reported an error when runnig the VS Code extension packaging pipeline.
https://github.com/ecadlabs/taqueria/runs/4987084269?check_suite_focus=true
```
Error: Command failed: npm list --production --parseable --depth=99999 --loglevel=error
npm ERR! code ELSPROBLEMS
npm ERR! missing: typescript@^4.5.4, required by taqueria-protocol@npm:@taqueria/protocol@0.0.1
```
`vsce` is unable to reference a linked dependency and throws an error. There is an open GH Issue for this problem https://github.com/microsoft/vscode-vsce/issues/203
---
Using `yarn` with `vsce` seems to solve the issue and the extension gets built successfully. I tested this change in this pipeline which completed successfully https://github.com/ecadlabs/taqueria/runs/4987473254?check_suite_focus=true
> ci: use `yarn` to package VSCode extension

- .github/workflows/main.yml
Removing the dependency of publishing the protocol on building the binaries
> removing dependency for publishing protocol on binaries

- taqueria-plugin-flextesa/docker/package.json
- taqueria-plugin-flextesa/package-lock.json
- taqueria-plugin-flextesa/package.json
- taqueria-plugin-flextesa/proxy.ts
- taqueria-plugin-ligo/package-lock.json
- taqueria-plugin-mock/package-lock.json
- taqueria-plugin-smartpy/package-lock.json
- taqueria-plugin-taquito/package-lock.json
- taqueria-plugin-teztnets/package-lock.json
- taqueria-protocol/taqueria-protocol-types.ts
Before CI/CD for the docker image, the plugin has a script to build the docker image using the name `taqueria/flextesa`. As such, within the plugin itself, that image was referenced as well.
Also fixed an issue with some static typing for protocol accounts defined in the taqueria-protocol package.
> Use flextesa-plugin-use-ghcr-image in flextesa plugin

- .github/workflows/npm-publish.yml
Updates the workflow to publish to npmjs.com with the `next` or `latest` tag depending on whether the GitHub workflow event is a `prerelease` or not
**Test Plan**
> refactor(ci): add next or latest tag depending on pre-release event

- .github/workflows/vscode-extension.yml
- package-lock.json
- package.json
- taqueria-vscode-extension/package.json
- taqueria-vscode-extension/src/lib/pure.ts
VSCode package requires node_modules to be included in the VXIS package, but now that we're using NPM workspaces, I believe that node_modules is in the root of the repo.
So I'm copying node_modules from the root before packaging.
In addition, the VSCode extension runs some child processes which need some adjustment to work on Windows.
> Attempt to fix vscode packaging

- taqueria-vscode-extension/src/lib/pure.ts
We were detecting Windows by looking for "win" in the process.platform property exposed by NodeJS. However, that wrongly detects macos as Windows because process.platform == "darwin" on macos.
> VSCode: Fix child process execution on all platforms

- code-of-conduct.md
Wholesale replacement of previous Contributor Covenant v.1.4 Code of Conduct with new v.2.1 better suited to moderation of community spaced such as Discord (see source at https://www.contributor-covenant.org/version/2/1/code_of_conduct/).
This change also replaces the reporting contacts with new email _abuse@ecadlabs.com_ and administrators/moderators in official community channels. Previous email no and keybase contacts no longer active.
> update Code of Conduct

- .github/workflows/docker-publish.yml
- taqueria-plugin-flextesa/docker/Dockerfile
Publishing docker images for `linux/amd64` and `linux/arm64/v8`
**Testing Plan**
Please see the [taqueria-flextesa](https://github.com/ecadlabs/taqueria/pkgs/container/taqueria-flextesa) images.
**Note**
We found that `linux/arm64` and `linux/arm64/v8` are essentially the same platform and will work for both if only one is specified.
Ref #206
> feat(ci): flexesa docker image on multiple platforms

- .github/workflows/vscode-extension.yml
- taqueria-vscode-extension/package.json
Similar to #185  we want to publish the VSCode Extension to the marketplace only when we officially publish a release on GH. 
The extension now is also being flagged as `pre-release` on the marketplace
Triggered a GH release to test the changes. Tha VSCode Extension isn't published anymore when a tag is pushed to `main` as the publishing job is skipped. https://github.com/ecadlabs/taqueria/actions/runs/1808354127
The extension is published to the VSCode marketplace when a GH release is published publicly.
https://github.com/ecadlabs/taqueria/actions/runs/1808354127
> ci(vscode): publish to VSCode marketplace when a GH release is published

- .github/workflows/main.yml
The `pr-comment` job in our pipelines create new comments for each commit we push to an existing PR. This creates a lot of noise when trying to review comments left on a PR and it also fills up email inbox with a lot of redundant emails.
This PR tweaks the job to update the existing comment left by the `github-action` bot instead of creating new ones.
New commits to this PR are updating the `github-action` bot comment instead of creating new comments
> ci: update existing github-bot comment in PRs instead of creating new ones for each commit

- website/docs/taqueria-dev/contributions.md
Revised Contributor Code of Conduct in documentation (https://taqueria.io/docs/taqueria-dev/contributions) to match the revised CCC in the project's root directory (https://github.com/ecadlabs/taqueria/blob/main/code-of-conduct.md).
> docs: update contributor code of conduct to match repo

- .github/workflows/main.yml
The Github reusable workflows introduced in #156 are tricky to work with when trying to update the template workflow. Currently we need to explicitly point to the branch we are working on in each reusable workflow instantiation. This is messy as we can easily forget to point the workflow back to `main` branch before merging a PR.
Github introduced [Reusable workflows can be referenced locally](https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/ ) on Jan 25th 2022 which should solve this issue most users are experiencing issues https://github.community/t/allow-reusable-workflows-to-be-located-at-arbitrary-locations-and-be-local/212745/5?u=danielelisi
> ci: Use local template reference for Github reusable workflows

- bin/build-all.sh
- bin/build-plugin.sh
- taqueria-plugin-flextesa/package.json
- taqueria-plugin-smartpy/package.json
- taqueria-plugin-taquito/package.json
- taqueria-vscode-extension/package.json
This is a temporary solution until we decide what to do with parcel and esbuild. Ideally we'd use the same build tool everywhere. We've had some trouble with esbuild in the vscode plugin, and then too, parcel has issues with segfaults.
For now, we keep running parcel in a loop until it completes.
> Fixes #315, handle parcel segfaults

- taqueria-utils/taqueria-utils-types.ts
The Future<L,R> type definition was aliased to unknown. I think this was something that got committed by mistake, as it should have been an alias to the type provided from the fluture library itself.
> Fixed type definition for Future

- tests/e2e/data/help-contents.ts
This PR is to fix the help messaging after introducing the new scaffolding code which added the scaffolding to the taq binary. The checks didn't stop the [merge](https://github.com/ecadlabs/taqueria/pull/139) even though the e2e tests failed (https://github.com/ecadlabs/taqueria/runs/5254016122?check_suite_focus=true).
> updated help contents for new scaffolding entries and message indenting

- website/src/components/Hero/Hero.js
This PR changes the target of the "Try the Beta" CTA button to target the installation guide
> Update install CTA link

- website/docs/intro.md
- website/docusaurus.config.js
- website/package.json
There is currently an unfixed bug with the docusaurus-gtg-plugin [details here](https://github.com/facebook/docusaurus/issues/2407) which prevents GTM from receiving events. This means technically there is no way to make Docusaurus GDPR compliant (requires gtag.js library) until this is fixed
In the meantime, I have reverted to referencing the GA4/UA compound property via the classic analytics.js lib
> Revert to direct GA properties

- website/docusaurus.config.js
- website/package.json
This PR implements GA properties for both UA and GA4 tags
It uses downgraded versions of each plugin that are compatible with the currently installed version of docusaurus
> Fix GA tagging issues

- .github/CODEOWNERS
We recently made the Taqueria team code owners of the /website/ dir to speed up PR approval and merging while reducing the burden on Jev and Michael W.
In addition to the /website/ dir being owned by @ecadlabs/taqueria , I think it makes sense for the Taqueria `readme.md` file to also have the taqueria team owning it due to the similarity in development and release to the website documentation
> Add taqueria team as codeowners for readme.md file

- website/docs/plugins/plugin-mock-plugin.md
- website/docusaurus.config.js
I've been investigating an SEO issue on the Taqueria site where every page is getting a 308 redirect. From what I can tell, this seems to be due to Cloudflare requiring a trailing slash. There are 2 options for resolving this:
1. Changing the build of the static site to add a trailing slash to all paths
2. Change the rules in Cloudflare
This PR implements a change to the Docusaurus config that forces a trailing slash (option #1) which should solve the issue if option #1 is the solution we decide to go with
> Force docusaurus to generate trailing slash on static site gen

- .github/workflows/docker-publish.yml
- .github/workflows/main.yml
We are encountering errors in our CICD when workflows are triggered from forked repositories e.g #438 . These workflows fail because of some of our jobs publish assets and require write permissions. This PR adds conditions to the workflows to only run the `run-tests` job when a PR is made from a fork. 
*Only run-tests job for fork PRs*
https://github.com/ecadlabs/taqueria/actions/runs/1959955142
> rafactor(ci): Only run-tests job for PRs from a fork

- website/robots.txt
This PR fixes an issue with GSC indexing the robots.txt file and disallows the email CDN page from being indexed
> Update robots.txt file to disallow CDN pages

- website/src/components/Features/Features.js
- website/src/components/Hero/Hero.js
This PR adds 2 trailing slashes to links on the landing page to fix an issue with them receiving a 308 redirect which is hampering SEO indexing and page ranking
> Fix 308 redirect issue

- .github/workflows/cla.yml
Adding teams is currently not supported in the action and we need to add each team member to the allowList
> chore: add ECAD memebers to the allow list

- taqueria-plugin-contract-types/example/contracts/example-contract-10.tz
- taqueria-plugin-contract-types/example/types-file/example-contract-10.code.ts
- taqueria-plugin-contract-types/example/types-file/example-contract-10.types.ts
- taqueria-plugin-contract-types/src/generator/typescript-output.ts
Claude found a case where a tuple parameter would cause a type error:
The original ligo signature was:
```
let update_token_metadata (p, s: (token_id * bytes) * storage): storage
```
- FIX this case by adding a _prefix to the argument name. `This has no runtime difference`, since argument names have no meaning to the caller at runtime
> BUG FIX: Integer param names

- .github/CODEOWNERS
Removing this because the sdet rule is overwriting the taqueria group rule and we want more eyes on PRs rather than less
> removed sdet rule from codeowners

- taqueria-flextesa-manager/package.json
- taqueria-protocol/taqueria-protocol-types.ts
- taqueria-sdk/index.ts
- taqueria-sdk/package.json
- taqueria-sdk/types.ts
It's initially meant to fix a code style, but later discovered that type checking was missing in the sdk and flextesa manager plugin workspaces.
Closes #561
> Closes #561 add missing typechecking to sdk and flextesa manager plugin

- npm.ts
- tests/e2e/utils/utils.ts
NOTE: This shouldn't resolve the scaffolding e2e tests.
See https://github.com/ecadlabs/taqueria/issues/578
I've worked around the issue by running `npm init -y` outside of the workspace, and then moving the test project directory back into the workspace. This is necessary as our test cases make assumptions that the directory is relative to the tests/e2e directory.
> Fixes #578, e2e tests not running locally

- quickstart.md
- website/docs/getting-started/plugin-basics.md
- website/docs/getting-started/quickstart.md
This is a short term fix for the issue of the quickstart.md in an initialized project being out of date. This PR updates the content with a modified version (shortened and enriched with plugin content) of the quickstart guide in the docs
In the future, this should be specialized as a series of step by step guides for common workflows a new user would be interested in
> Update the quickstart.md file injected into new projects

- .gitignore
- taqueria-sdk/index.ts
- taqueria-sdk/package.json
- taqueria-sdk/types.ts
This was cherry-picked from a change I made in a different branch for the jest plugin. It also includes adding an ESM module as a build target.
> Fixed issue with SDK not compiling due to x32 being used.

- .github/workflows/main.yml
Removing the `vscode-extension-workflow` dependency for the release
> chore: removed release dependency on the vscode workflow

- .github/workflows/main.yml
In the `main.yml` workflow there is an assertion made after the binaries are compiled:
```shell
[[ $(./"${{ matrix.taqueria_bin }}" init -p ./test_project) == "Project taq'ified!" ]] 
```
The assertion no longer works on the windows runner. This PR aims to fix that by making a new assertion that checks if the `config.json` file exists in the `test_project/.taq/` directory
> fix: fix the failing assertion when the test project is initialized

- cli.ts
This PR makes 2 small changes to the scaffold task:
- It removes the `quickstart.md` file injected by `taq init`
- It changes the default scaffold to be `hello-tacos`
> Refactor Scaffold Task

- .husky/pre-commit
- package-lock.json
- package.json
We generate a deno.lock file, which is synonymous with package-lock.json for Node, in a pre-commit hook.
However, if someone changes a file in the website, SDK, or a plugin, then we don't need to re-generate the lock file.
This PR adjusts things so that the deno.lock file is only generated when a file relevant to the CLI is modified.
> Adjusted pre-commit hook to only generate Deno lock file CLI source has changed

- taqueria-vscode-extension/package.json
- taqueria-vscode-extension/src/lib/gui/ArtifactsDataProvider.ts
- taqueria-vscode-extension/src/lib/helpers.ts
Implements #1019
> Currently, we have one TreeView that shows contracts.
But some of the commands that should be run on artifacts are enabled on that view.
So if a user runs an artifact command (like originate) on a contract, the TVsCE has a logic that decides which artifact to run this command on.
This logic is super simple now, and fails in many cases: it replaces the file extension of the contract with .tz to get the artifact file name. This does not work for smartpy.
So a better option would be to have a better distinction of contracts and artifacts. So the user can run the right commands on each.
> Display separate artifacts tree view with originate button

- .github/workflows/workflow-pruning.yml
This change will add a workflow that will delete old workflow runs that are no longer required. In the past we have had incidents where old workflow runs can cause confusion when trying to debug a specific issue. One such incident happened previously during a release https://ecadlabs.slack.com/archives/C036G3SVA4Q/p1656525987109809.
Here is an example of some workflows that no longer exist
There were a lot more than those listed in the screenshot that were manually deleted. 
Unfortunately we can not see this workflow in action until it is merged into main. I tested it out successfully in the `taqueria-github-action` repo if anyone wants to see how it works before merge.
https://github.com/ecadlabs/taqueria-github-action/runs/7774502009?check_suite_focus=true
> chore: add workflow to delete old workflows

- taqueria-plugin-ligo/compile.ts
- taqueria-plugin-ligo/index.ts
- taqueria-plugin-ligo/ligo.ts
- taqueria-sdk/index.ts
- tests/e2e/taqueria-cli-scaffolding-functional.spec.ts
- tests/e2e/taqueria-cli-scaffolding-init.spec.ts
Fixes #1168 
We did not have means to compile storages and parameters in the LIGO plugin. This change adds those features by introducing a naming convention. e.g. `taq compile hello.mligo` will compile the contract like before, but `taq compile hello.storages.mligo` and `taq compile hello.parameters.mligo` will compile the LIGO storage and parameter expressions defined in those files respectively. Furthermore, contract compilation will automatically perform compilation of its associated "storages" and "parameters" files.
----------------------------------------------------------------------------------------------- …
> 🏗️ PR ➾ LIGO improvements part 1 (compile storage and parameter)

- taqueria-plugin-contract-types/example/contracts/subdir/example-contract-0.tz
- taqueria-plugin-contract-types/example/contracts/subdir/subsubdir/example-contract-0.tz
- taqueria-plugin-contract-types/example/types-file/subdir/example-contract-0.code.ts
- taqueria-plugin-contract-types/example/types-file/subdir/example-contract-0.types.ts
- taqueria-plugin-contract-types/example/types-file/subdir/subsubdir/example-contract-0.code.ts
- taqueria-plugin-contract-types/example/types-file/subdir/subsubdir/example-contract-0.types.ts
- taqueria-plugin-contract-types/src/cli-process.ts
- taqueria-plugin-contract-types/test/generator.spec.ts
- tests/e2e/taqueria-plugin-contract-types.spec.ts
- Contracts nested in sub directories will now have the correct relative path to the type aliases file
- Resolves #1113 
- Add contract type tests to main tests
- Tests are based on a snapshot of manually verified type generation results
> 1113 Fix contract types sub dir

- .github/workflows/main.yml
N/A
The publish step for the Contract Types plugin has been disabled since the 0.10.0 release of Taqueria. As such, the plugin is now 2 versions behind the rest of Taqueria and has caused a user-reported bug. This PR re-enables the skipped steps in `main.yml` 
> Note: I have manually published v0.12.0 of the plugin  
N/A
> 🏗️  ➾Re-enable Contract Types Plugin Publishing

- .github/workflows/npm-publish.yml
- bin/deploy.sh
During the prerelease for `v0.13.16` we found that package dependencies were not being updated and that packages were being published with the `preview` tag instead of `next`. This change is what was used to fix the release process for the prerelease and should be added before the next relreaes.
> fix(ci): fixed deploy script packages and prerelease tag

- website/docs/getting-started/installation.mdx
The quickstart page of the website and docs needs to be updated to reflect the version number change. Currently the docs indicate that when a user runs `taq --version`, the output with show `v0.10.0`. This is not the case and needs to be updated to `v0.16.0`. For future releases, this file needs to be updated with the release version number.
> fix(docs): '--version' output show version 0.16.0

- taqueria-plugin-ligo/README.md
- taqueria-plugin-ligo/_readme.eta
- taqueria-plugin-ligo/compile.ts
- taqueria-plugin-ligo/index.ts
- taqueria-plugin-ligo/ligo.ts
- taqueria-plugin-ligo/test.ts
- tests/e2e/data/hello-tacos-invalid-tests.mligo
- tests/e2e/data/hello-tacos-tests.mligo
- tests/e2e/data/help-contents/help-contents.ts
- tests/e2e/data/help-contents/ligo-contents.ts
- tests/e2e/taqueria-plugin-ligo.spec.ts
- tests/e2e/taqueria-plugin-multiple-test-plugins.spec.ts
Fixes #1166 
This PR adds a new task from the LIGO plugin called `test`, which allows LIGO devs to test their LIGO code natively. This facilitate unit tests and e2e tests for contracts.
Command syntax: `taq test <sourceFile>`
Variable names that are prefixed with `test` will be included in the tests (this comes from LIGO).
Normally, you would have a `counter.mligo` contract and `testCounter.mligo` file that tests `counter.mligo` where at the beginning of `testCounter.mligo`, you have the line `#include "counter.mligo"`.
For example (first is `counter.mligo` and second is `testCounter.mligo`):
```
type storage = int
type parameter =
Increment of int
| Decrement of …
```
> Add test task for ligo plugin

- taqueria-protocol/package.json
- taqueria-protocol/tsconfig.json
Fixes an issue where Taqueria Protocol cannot be built on Node v16.16.0 or later - v16.5.0 appears to work fine.
tsup is used to build our bundle and dts files. However, tsup defers dts generation to rollup-plugin-dts, which appears to be having issues with the latest version of node. Thus, I've adjusted our build routine for the protocol package to use the typescript compiler for dts file generation, and use tsup for everything else.
Asking Alex to build locally on specific versions of NodeJS. …
> Fix build issues for taqueria-protocol on node v16.16.0+

- .husky/pre-commit
Remove the husky commit hook that will generate docs using eta templates and commit them without the user knowing. This could be added as a manual job with documentation that informs the developer on how to change the docs.
> chore: remove docs husky hook

- .github/workflows/main.yml
Some tests are failing because the docker image is not being built before the tests. This is a temporary fix to add a docker build step before the test run. The more permanent solution is that the docker image should be cached
> fix(ci): added docker build before tests

- .github/workflows/main.yml
- .github/workflows/vscode-extension.yml
The VSCode publish job is being run for pull requests. This should not be the case and this PR aims to change that
> chore: prevent vsix publishing on PR

- taqueria-protocol/SanitizedArgs.ts
Fixes #1223
A Zod schema had given a default to env so that if we don't specify `--env` in the CLI, it is always set to 'development', never honouring the default environment set in the config file.
> Remove default from Zod schema for env field

- taqueria-vscode-extension/CHANGELOG.md
- website/docs/scaffolds/taco-shop.mdx
The docs needed some clarification so the change could be made without a linter error
CLOSE #1478 
- [x ] ⛵ My code builds cleanly, and I have manually tested the changes
- [x ] 🤿 Corresponding changes have been made to all documentation
changed some worried in a cod and removed an extra line of code from the example
to follow the doc instructions now with the fix and not have errors
- [x ] 🛠️ Fix ➾
> made doc corrections to clarify adding contract to taco shop react app config

- bin/build-all.sh
- tests/package.json
Reintroduce `maxWorker=1` to the E2E Jest tests. This fixes E2E tests failing on mac runners. Failed job example
https://github.com/ecadlabs/taqueria/actions/runs/3517074829/jobs/5896661542
> Reintroduce maxWorker=1 for E2E Jest tests

- nx.json
NX is configured to cache a number of tasks including  `build:docker`. This is causing issues with outdated Docker images when switching branches and running `build:docker` which seems to not generate the correct Docker image for the branch.
This PR disables caching for `build:docker` to ensure  new Docker images are always generated 
> 🛠️ Fix ➾ (build) removed caching for build-docker

- cli.ts
Removing left-over debugging statement, which outputs the contents of the scaffold.json file:
```
{
"postInit": "npm run setup"
}
```
> Don't log scaffold.json contents when scaffolding

- .github/workflows/main.yml
- bin/build.sh
- bin/debug.sh
- bin/run.sh
- bin/set-vars.sh
- test.sh
After the previous changes to the build and CI, we still had failures. We decided to centralize the calculation of TAQ_VERSION and BUILD in once place. This will make it easier to change in the future, and will make it easier to debug if things go wrong.
Removed all calculation of TAQ_VERSION and BUILD variables from `.github/workflows/main.yml` and moved all to `bin/set-vars.sh` which is sourced before all build and test actions.
> 🛠️ Fix ➾ Set TAQ_VERSION and BUILD in one script to unify CI and local build and test

- .github/workflows/main.yml
- .github/workflows/vscode-extension.yml
- bin/build-all.sh
- package.json
`lerna bootstrap` is a legacy command that was used to install and link all dependencies for packages in a monorepo.
[Lerna docs suggest to stop using `lerna bootstrap](https://lerna.js.org/docs/features/legacy-package-management#background)` and instead let the package manager handle this task as now it's handled by NPM Workspaces when running `npm ci` and `npm install`.
This PR removes all references of `lerna bootstrap` in the codebase
This PR removes all references of `lerna bootstrap` in the codebase
- Searched trough the repo for `lerna bootstrap` and removed its occurrences. 
- All CI workflows pass
> 🧽 Chore ➾ Delete legacy lerna bootstrap commands

- taqueria-vscode-extension/package.json
- taqueria-vscode-extension/src/lib/helpers.ts
This PR prevents running "Compile Current File" command when the text editor is not focused (e.g. clicked on the Taqueria output panel).
This PR adds a runtime check so that the "Compile Current File" command is not executed when the text editor is not focused for any reason.
It also adds a condition for TVsCE `enablement` so that the command is displayed in the command palette only if the text editor has focus.
1. Open taquified workspace with extension …
> 🛠️ Fix ➾ Prevent running compile current file command if the text editor is not focused

- tests/package.json
When running test:unit:deno:debug, there needs to be an import-map specified.
See https://github.com/ecadlabs/taqueria/issues/1563
Added the import-map option to the `deno test` command.
> Fixes #1363, Adds import-map to test:unit:deno:debug task

- taqueria-vscode-extension/package.json
- taqueria-vscode-extension/src/lib/gui/ArtifactsDataProvider.ts
- taqueria-vscode-extension/src/lib/gui/ContractsDataProvider.ts
- taqueria-vscode-extension/src/lib/gui/TaqueriaDataProviderBase.ts
- taqueria-vscode-extension/src/lib/helpers.ts
We can see the contracts and artifacts in the sidebar, but clicking on them did not open them in the editor.
Now clicking on contracts and artifacts in the sidebar opens them in the text editor
> Open Contracts and Artifacts when double-clicking a TreeViewItem in Taqueria sidebar

- taqueria-plugin-flextesa/proxy.ts
- taqueria-vscode-extension/src/lib/gui/SandboxesDataProvider.ts
A previous change in how the Flextesa Plugin names its containers was not reflected in the VsCode Extension
Updated the container names that the VsCode Extension is looking for. Also added a comment to the function in Flextesa plugin to remind synchronizing the other one.
> Fix: Change Container Name in VsCode Extension to Match Flextesa Plugin

- .github/workflows/main.yml
References #1602
In a team call this morning we decided to drop support for native Windows binary.
Delete references to Windows in our Github workflow files
> 🧽 Chore ➾ Stop building native Windows binary

- taqueria-plugin-flextesa/tzkt-manager.ts
When we start the Sandbox, four containers start:
- The Flextesa Sandbox
- Postgres
- TzKt.Sync that reads from the sandbox and updates postgres
- TzKt.Api that reads from postgres and serves API calls.
After starting, TzKt.sync will apply the database schema to postgres. TzKt.Api keeps checking this schema to make sure it can work with that document. It does this 30 times. This has been enough for their own setup (on a server, where they can start them separately and wait for sync to apply the schema) and on my machines.
But on some machines, this is not enough.
So here is our solution:
- On our version of TzKt we increase that to 120.
- Open a ticket on their repo to read that from settings (which can then be overriden in environment variables)
- When they merge that and release a .net …
> Fix: Have TzKt.Api do more retries for Database Schema before failing

- .github/workflows/main.yml
- .github/workflows/vscode-extension.yml
We decided to downgrade Deno to version `1.23.1` for our GH workflows as this is the version used by our developers. 
I've created a global env variable for Deno version and referenced it in each job. There is an hacky workaround for exposing the env variable to reusable workflow as I was hitting the bug mentioned in https://github.com/orgs/community/discussions/26671
GH Workflows should pass
> 🧽 Chore ➾ Downgrade Deno version to v1.23.1 in GH Workflows

- bin/build-all.sh
- bin/build.sh
Taqueria requires Deno v1.23.X to build. This branch adjusts the build.sh and build-all.sh scripts to ensure that Deno is installed and set to the correct version.
*NOTE:  I've set the target for this PR to prerelease-0.25.0 so that you only see the actual files changed in this PR*
Modified build.sh and build-all.sh scripts. 
I've tested that if I have Deno v1.24 installed I'll get an error when running `npm run build-all`. I've also verified that the error goes away when I have v1.23 installed.
> Check for deno version

- taqueria-vscode-extension/src/lib/helpers.ts
- taqueria-vscode-extension/src/lib/pure.ts
The CLI check used to call `taq testFromVsCode` and depended on `OK` to be returned from that command. A PR has broken this.
Changed the logic to run `taq --version --fromVsCode` instead, so that we can show the Version as well.
The version is still not shown, as I do not know how to show it in `viesWelcome.content`. Asked the VsCode team in their slack. Once we know it, showing it should be two lines of change.
> Fix Taq check in VsCode

- taqueria-sdk/index.ts
The taq CLI communicates with plugins by passing options as CLI arguments. In retrospect, I think passing via stdin would have been more appropriate but that's a different issue. :)
In any case, a CLI argument of `--debug 'false'` was being wrongly interpreted, such as the ParsedArgs object would have the `debug` property set to `true` instead of `false`. This PR fixes that.
Fixed the logic of the formatArgs() function in the SDK.
>  🛠️ Fix ➾ Interpretation and parsing of boolean options given to a plugin

- taqueria-plugin-smartpy/README.md
- taqueria-plugin-smartpy/_readme.eta
- taqueria-plugin-smartpy/common.ts
- taqueria-plugin-smartpy/test.ts
Fixes #1597
Added ability to override SmartPy CLI by providing an environment variable called `TAQ_SMARTPY_VERSION`, similar to how it's done in other plugins.
> ✨ Feature ➾ added ability to override versions in SmartPy and fix error reporting issue during SmartPy compile and test

- .github/workflows/main.yml
- bin/build.sh
- bin/debug.sh
- bin/run.sh
Relates to #1646
Taqueria dev team reported errors with dependency imports when building Taqueria binaries locally. 
```
error: Import 'https://deno.land/x/ramda@v0.27.2/source/minBy.js' failed: 500 Internal Server Error
at https://deno.land/x/ramda@v0.27.2/source/index.js:137:34
```
I've noticed that our build scripts set the `DENO_DIR` for dependencies caching inside the Taqueria project. These caches get deleted when running `git clean -fdx` 
> 🛠️ Fix ➾ Use default location for Deno dependency caching

- taqueria-config.ts
- taqueria-plugin-taquito/originate.ts
- taqueria-protocol/types.ts
- taqueria-sdk/index.ts
- tests/e2e/data/taquito-funding-instructions.txt
- tests/e2e/taqueria-plugin-taquito.spec.ts
- website/docs/config/networks.mdx
Fixes #1598
Added the ability to deploy and interact with mainnet.
- Allow mnemonic to be specified in the config.
- Create a new environment called production that points to a newly created network called mainnet.
> ✨ Feature ➾ added ability to deploy to mainnet and interact with contracts deployed there

- cli.ts
- npm.ts
- plugins.ts
- tests/e2e/taqueria-plugin-ligo.spec.ts
I forgot that in the internal task refactor work we re-generate the ephemeral state after the install task is run. However, this was using an outdated version of LoadedConfig in memory (the plugins property was out of date).
Ensures that you can do the following and get contextual help:
```
taq init test-project && cd test-project && taq install [path to local flextesa plugin] && taq start sandbox --help
```
Expected output:
```
taq start sandbox [sandboxName]
Starts a flextesa sandbox
Positionals:
sandboxName  The name of the sandbox to start
Options:
-p, --projectDir  Path to your project directory               [default: "./"]
-e, --env         Specify an environment configuration
--version     Show version number                                [boolean]
--build …
```
> 🛠️ Fix ➾ Don't generate ephemeral state twice when installing/uninstalling plugins

- package-lock.json
- taqueria-plugin-flextesa/package.json
- taqueria-plugin-flextesa/proxy.ts
In our config.json file, we can omit the protocol to use in our flextesa sandbox. In that case, the flextesa image would just use 'Alpha' as the protocol hash when starting the node. This PR adjusts that so that the latest protocol hash supported by the image is used instead.
- getProtocolsSupported() is now memoized so that it can be called multiple times without having to call a docker child process for each invocation
- getProtocolKind() will now return the hash of the latest protocol as opposed to Alpha
In main, start a sandbox and then run `docker logs` against the container running tztk-sync and you'll see errors.
Use this branch, start a sandbox, and then run `docker logs` against the container running tztk-sync and you'll see _no_ errors.
> 🛠️ Fix ➾ Use the hash of the latest protocol supported by the image as opposed to using Alpha

- taqueria-plugin-mock/index.js
- taqueria-sdk/index.ts
- tests/integration/plugin-mock.spec.ts
When the SDK encountered a zod error (or any error), it would just output the error to stderr using `console.error(err)`.
Instead, we should provide more granular error handling and too, ensure that our output is sanitized (so that it doesn't leak private information).
- Added the start of more granular error handling in the SDK's Plugin.create() call
- Only output the message unless the `--debug` flag is provided.
- Sanitize output to swap any private or secret keys with _[hidden]_ as a value.
- Extended the mock plugin to provide a response for invalid schema data
I added an integration test using the mock plugin to assure that the error messaging is appropriate.
> 🛠️ Fix ➾ Added better error handling to the SDK

- tests/jest.config.e2e.ts
- tests/jest.config.integration.ts
closes #1737 
the pinata .env preset for tests is no longer required and has been removed
The pinata .env preset for tests is no longer required and has been removed
test run and pass
> remove pinata preset requirement

- taqueria-plugin-flextesa/tzkt-manager.ts
Previously we had to maintain our own fork and docker image of TzKt because:
1. TzKt was using .net 5 which was not running on m1 mac
2. TzKt could not work with protocol Alpha
3. TzKt.Api did not wait long enough (in our setup) for TzKt.Sync to create the database schema.
The Baking Bad team had decided to skip .net 6 because of a Json serialization incompatibility, but when they migrated to .net 7, we could use their image. We opened a PR: baking-bad/tzkt#139 to fix our other problems and now we can use their image.
Switched to Official TzKt images from BakingBad
> Use official TzKt images

- taqueria-plugin-contract-types/tasks.ts
Fixes #1284
During contract type generation, exclude all non-contract files such as storage (default or not) files, parameter files, and expression files.
> 🛠️ Fix ➾ During contract type generation, exclude all non-contract files such as storage files

- taqueria-plugin-ligo/README.md
- taqueria-plugin-ligo/_readme.eta
- taqueria-plugin-ligo/common.ts
- taqueria-plugin-ligo/compile-all.ts
- taqueria-plugin-ligo/compile.ts
- taqueria-plugin-ligo/index.ts
- taqueria-plugin-ligo/main.ts
- taqueria-plugin-smartpy/README.md
- taqueria-plugin-smartpy/_readme.eta
- taqueria-plugin-smartpy/common.ts
- taqueria-plugin-smartpy/compile.ts
- taqueria-plugin-smartpy/compileAll.ts
- taqueria-plugin-smartpy/index.ts
- taqueria-plugin-smartpy/main.ts
Fixes #1576
Implemented `taq compile-all` for the LIGO and SmartPy plugin which compiles all LIGO main contracts (contracts with a main function) and all SmartPy contracts with at least one SmartPy compilation target, respectively.
> ✨ Feature ➾ implement `taq compile-all` for the LIGO and SmartPy plugin

- taqueria-vscode-extension/src/lib/helpers.ts
Closes #1772 
Closes #1781 
TVsCE monitors for changes to the `.taq/config.json`. After configuration redesign, we now have files like `.taq/config.local.development.json`. Changes to these files should also be monitored. This was the root cause for bug #1772 
Watch changes to all files matching `.taq/config*.json` such as `.taq/config.local.development.json`.
> Fix Monitoring for Changes in TVsCE

- taqueria-plugin-core/clean.ts
- taqueria-plugin-flextesa/tzkt-manager.ts
TzKt images released by Baking Bad are not running on m1 macs.
Rolled back to the TzKt images maintained by ECAD
> Rollback TzKt to Ecad images

- taqueria-plugin-ligo/common.ts
- taqueria-plugin-ligo/compile-all.ts
- taqueria-plugin-ligo/compile.ts
- taqueria-plugin-ligo/test.ts
- taqueria-plugin-smartpy/common.ts
- taqueria-plugin-smartpy/compile.ts
- taqueria-plugin-smartpy/compileAll.ts
- tests/e2e/smartpy-plugin-e2e-tests.spec.ts
Fixes #1764
LIGO and SmartPy compile and compile-all only worked when executed in the root directory of a TAQ project. Now users can execute them in any subdirectory within root.
> 🛠️ Fix ➾ Make compile and compile-all work when users exec them in contracts dir

- taqueria-sdk/index.ts
There was a change made to execCmd's rejection value to include stderr and stdout properties. However, this broke tasks which explicitly checked whether the rejection value was an instanceof the Error prototype.
I've modified the execCmd function in such that the rejection value is always an Error instance, but with stderr and stdout added as runtime properties.
This assures that the code in the ligo plugin's `test` task works as it should:
```
export const emitExternalError = (err: unknown, sourceFile: string): void => {
sendErr(`\n=== Error messages for ${sourceFile} ===`);
err instanceof Error ? sendErr(err.message.replace(/Command failed.+?\n/, '')) : sendErr(err as any);
sendErr(`\n===`);
};
```
It also ensures that the code in the flextesa plugin that is using …
> 🛠️ Fix ➾ execCmd should always reject with Error instance with stdout and stderr properties

- taqueria-sdk/index.ts
When fixing a previous bug, a new one was introduced. I had made a typo and returned the wrong return value, returning the input value instead of the desired output value.
In toErrorwithProps, return `retval` - not `err`.
> 🛠️ Fix ➾ bug introduced in toErrorWithProps. Wrong return value.

- taqueria-protocol/scripts/post-ts-to-zod.ts
- taqueria-protocol/types-config-files.ts
- taqueria-toolkit/TaqError.ts
- taqueria-toolkit/index.ts
- taqueria-toolkit/v1.ts
- taqueria-toolkit/v2.ts
Previously, the API of the toolkit included two functions that would only work when given Config V1 objects.
This PR adds a V2 namespace for functions that work with Config V2 objects.
- In my last refactor, I introduced a `loadFromEnv` function which has been renamed to `withEnv`, made private, and used internally by two new public functions, `getConfigV1` and `getConfigV2`. These will return a representation of the project's form in either V1 or V2 respectfully, regardless of what version the actual config file is using. This facilitates backwards and frontwards compatibility.
- Introduces the V2 module, which is the start of an API for working with projects using the V2 config. This API is limited to just three functions for now, but we can flesh this out later. …
> 👷 Refactor ➾ Added V2 API for the toolkit

- taqueria-protocol/types-config-files.ts
The `taq transfer` task was not finding aliases in the Config runtime object due to a mis-transformation from V2 config.
Added `aliases` to network config of the runtime Config object.
Re-run the steps in the issue.
> 🛠️ Fix ➾ Closes #1824, transfer task not finding aliases

- tests/e2e/contract-types-plugin-e2e-tests.spec.ts
- tests/e2e/taquito-plugin-e2e-tests.spec.ts
Issue #1711 was created to fix contextual help with various tasks:
- generate
- transfer
- call
- fund
- instantiate-account
The contextual help was actually for these tasks, but the tests needed some adjustment.
Adjusted tests:
- The test used to assert that contextual help was working for the `generate` task was missing a `cwd` option.
- The tests in the taquito e2e suite was producing a false-negative as it was looking for a string that was split between two lines.
Re-run existing tests.
> 🛠️ Fix ➾ Closes #1711, update tests to assert that contextual help is working

- .vscode/launch.json
- taqueria-vscode-extension/src/lib/LogHelper.ts
- taqueria-vscode-extension/src/lib/helpers.ts
In TVsCE it is useful to be able to specify which version of plugins should be installed. Previously we only had the option to install the release ones or the locally built ones.
The environment variable `PluginVersionToInstall` can be left empty, which installs the release plugins, or `next` which installs the prerelease plugins.
If set to `local`, it will install plugins from the locally built repository. This expects that the `taq` binary is found from that repository.
> Ability to install plugins with specific version in TVsCE

- taqueria-vscode-extension/src/lib/gui/ArtifactsDataProvider.ts
- taqueria-vscode-extension/src/lib/gui/ContractsDataProvider.ts
- taqueria-vscode-extension/src/lib/gui/helpers/GrouppedFileItem.ts
- taqueria-vscode-extension/src/lib/helpers.ts
We have conventions for files that are storage, argument or expression for a main contract file. Like `contractName.default_storage.tz`. The contracts and artifacts treeviews were flat. It is nice to show these files as children nodes to the main contracts.
The Contracts and Artifacts TreeViews now recognize the patterns that relate contracts to their storage, argument and expression files, and show them as subtrees.
> Group Contracts and Artifacts in TreeViews

- taqueria-plugin-mock/package.json
- taqueria-protocol/SanitizedArgs.ts
When a task is prompting for consent, but the end-developer specifies `--yes` or `-y`, then the task should assume `y` to all prompts.
Added a preprocess to the SanitizedArgs schema, in such that it checks if either of `y` or `yes` is present.
> 🛠️ Fix ➾ Closes #1778, allowing `yes` to all prompts

- taqueria-plugin-flextesa/index.ts
- tests/e2e/flextesa-plugin-e2e-tests.spec.ts
With the new environment refactor, an environment can only ever have one sandbox associated with it, and thus, we don't need to specify a sandbox name for any task provided by the flextesa plugin.
> 🛠️ Fix ➾ Don't require sandbox name for any task

- taqueria-plugin-flextesa/index.ts
- taqueria-plugin-flextesa/proxy.ts
- taqueria-plugin-taquito/common.ts
- taqueria-plugin-taquito/fund.ts
- taqueria-plugin-taquito/index.ts
- taqueria-plugin-taquito/main.ts
- taqueria-plugin-taquito/originate.ts
- taqueria-plugin-taquito/transfer.ts
- taqueria-plugin-taquito/tsconfig.json
- Added a new task to the flextesa plugin called `restart sandbox`. 
- Adjusted all tasks of the taquito plugin to accept a `timeout` option, with a default value of 40 seconds.
- All taquito tasks (originate, fund, and transfer) will continuously retry upon failure up to the timeout value above). Closes #1846
> 🛠️ Fix ➾ Add restart sandbox task, and ensure that all taquito tasks will retry until max timeout elapsed

- lerna.json
- package-lock.json
- package.json
- taqueria-analytics/package.json
- taqueria-plugin-archetype/package.json
- taqueria-plugin-contract-types/package.json
- taqueria-plugin-core/package.json
- taqueria-plugin-flextesa/package.json
- taqueria-plugin-ipfs-pinata/package.json
- taqueria-plugin-jest/package.json
- taqueria-plugin-ligo/package.json
- taqueria-plugin-metadata/package.json
- taqueria-plugin-smartpy/package.json
- taqueria-plugin-taquito/package.json
- taqueria-plugin-tezos-client/package.json
- taqueria-protocol/package.json
- taqueria-sdk/package.json
- taqueria-toolkit/package.json
- taqueria-vscode-extension/package.json
- website/docs/release-notes.mdx
| Details     |               |
| ----------- | ------------- |
|Release Date | Feb 16, 2023  |
|Release Type | Minor         |
|Release Page | [v0.28.2](https://github.com/ecadlabs/taqueria/releases/tag/v0.28.3) |
- The `transfer` and `deploy` tasks will now retry if an error occured trying to forge or inject an operation. The tasks will be retried until the max timeout is reached (set to 40 seconds by default).
- Add a `--timeout` option to both the `transfer` and `deploy` tasks to adjust the max timeout before giving up on forging and injecting an operation.
- Tasks provided by the flextesa plugin no longer require a sandbox name, which is now inferred from the environment. For example, to start a sandbox you would execute `taq start sandbox` instead of `taq start sandbox local`
- Adds …
> 🚀 Release ➾ v0.28.3

- taqueria-plugin-ligo/ligo.ts
Fixes a problem with file permissions created by docker when invoking the `taq ligo` task in WSLv2 environments.
Don't assume that GID environment variable exists.
> 🛠️ Fix ➾ Ensure that docker ownership of files created by ligo task work on WSLv2

- README.md
- website/docs/tasks/init.md
> chore: fix typos and link update
