.github/workflows/npm-publish.yml
The version should not change for official release publishing
=> fix(ci): npm official release publish version from package.json

README.md
The taqueria binary was renamed from `taqueria` to `taq`
=> Update README.md to reference binary as 'taq' not 'taqueria'

.github/workflows/vscode-extension.yml
Ref #97  
Fix the Windows VSCode pipeline
Linking a succeeded pipeline https://github.com/ecadlabs/taqueria/actions/runs/1774524921
=> Use expression to render env variables in VSCode pipeline

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> Remove contact details from bug_report.yml and feature_request.yml

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Minor wording updates for feature request and bug report.
Added an area for screenshots and images to bug request.
=> Update feature request and bug report

taqueria-vscode-extension/src/extension.ts, taqueria-vscode-extension/src/lib/pure.ts
Fixes a typo when detection Windows platform for VS Code.
=> Fixes vscode windows detection

.husky/pre-commit, tests/unit/taqueria-utils/taqueria-utils.test.ts
This is a PR to add a commit hook that will run the unit tests whenever a user commits some changes. It assumes the following:
- User has run npm install
- User has installed deno as part of the setup for unit testing
=> 267 run unit tests on commit

website/docs/roadmap.md, website/sidebars.js
Adds a docusaurus page with the Taqueria roadmap
=> Add roadmap page

taqueria-plugin-taquito/originate.ts
Error handling was conducted incorrectly in the Taquito plugin. This branch adjusts the taquito plugin to throw and handle errors in the same way that we do in the LIGO plugin, which assures that the errors propagate correctly and are rendered in VSCode properly.
=> Fixes #248, propgate storage up to VSCode

.github/workflows/main.yml, tests/e2e/utils/utils.ts
Adding in SDK build step for integration tests
=> Adding build step for SDK in integration tests

README.md
@mweichert , please add your feedback and confirm that I didn't miss any of the requirements for building Taqueria locally when you can
I seem to remember using Rust somewhere but I can't find it in any of the build scripts or pipeline yml files
=> Add build dependencies to readme.md

website/docusaurus.config.js
=> Swap GA4 tag to legacy

.github/workflows/main.yml, tests/e2e/taqueria-cli-commands.spec.ts
Added in a step to notify the e2e notifications channel in slack when a job fails
=> added in step to notify channel when e2e tests fail

.github/workflows/codeql-analysis.yml, taqueria-protocol/taqueria-protocol-types.ts
This PR adds the CodeQL workflow to enable code scanning on a scheduled basis as well as for pull requests
*Example of issues found by CodeQL*
*Example of CodeQL finding no issues after fix*
https://github.com/ecadlabs/taqueria/security/code-scanning?query=pr%3A518+tool%3ACodeQL
*Searchable history of branch issues*
=> feat(ci): add CodeQL workflows

.github/workflows/main.yml, tests/e2e/taqueria-cli-commands.spec.ts
Fixing node version to fix integration tests
=> fixing node version for tests to enable integration test to pass

cli.ts, taqueria-utils/taqueria-utils.ts
Fixes #390 and #530
NOTE, there is a question whether implementing #530 makes sense or not.
=> NEW - Fixes #390, remove .git directory from scaffold

design-docs/state-architecture.md
=> Added initial draft of design doc for state architecture. Fixes #548

website/src/components/Features/Features.js
Updated homepage content for Archetype release.
=> Updated content for Archetype

taqueria-plugin-tezos-client/README.md, website/docs/plugins/plugin-tezos-client.mdx, website/sidebars.js
First draft of the tezos client plugin docs implemented here, ready for feedback / input @jchenche @mweichert
=> Add plugin-tezos-client docs for website

taqueria-vscode-extension/src/extension.ts, taqueria-vscode-extension/src/lib/helpers.ts, taqueria-vscode-extension/src/test/suite/MockedObject.ts, taqueria-vscode-extension/src/test/suite/extension.test.ts, temp-project/quickstart.md, test-flextesa/quickstart.md, test-refactor/quickstart.md, validation-test/quickstart.md
=> Added dependency injection to vscode extension

website/docs/getting-started/installation.mdx
Update install instructions version to 0.3.1
=> Update version on install instructions page

website/docs/getting-started/quickstart.mdx
PR to close issue #782 
There was a typo on the quickstart.mdx page in the Taqueria docs.
=> correct the wether typo in quickstart.mdx

.github/workflows/main.yml
Removed the dependency on the uploaded `vsix` file in the release job
=> chore: removed the wget command to download the vsix file

taqueria-vscode-extension/.vscodeignore, taqueria-vscode-extension/package.json
=> Remove non-vscode files from vsix bundle. Bump extension version #

cspell.json, package-lock.json, taqueria-vscode-extension/package.json, taqueria-vscode-extension/src/extension.ts, taqueria-vscode-extension/src/lib/helpers.ts
=> show/hide & enable/disable tasks

cspell.json, taqueria-vscode-extension/package.json, taqueria-vscode-extension/src/extension.ts, taqueria-vscode-extension/src/lib/helpers.ts
=> Implement missing functionality in TVsCE

taqueria-plugin-taquito/originate.ts
=> Show error for all contracts that lack storage

taqueria-vscode-extension/package.json
=> change extension type to workspace

taqueria-protocol/EphemeralState.ts
(cherry picked from commit b0dbff7a3f004b0488b17d4d5a9b9d3fee49be16)
=> FIX taq runtime bug

taqueria-plugin-archetype/archetype_template.ts, taqueria-plugin-archetype/createContract.ts, taqueria-plugin-archetype/index.ts, taqueria-plugin-ligo/createContract.ts
=> Add contract template for Archetype

cli.ts, import_map.json, taqueria-protocol/ScaffoldConfig.ts, taqueria-protocol/taqueria-protocol-types.ts
Will invoke `postInit` using the shell if it exists as a property of the scaffold.json file.
=> Call scaffold.json's postInit script when setting up scaffold

package-lock.json, taqueria-plugin-archetype/package.json, taqueria-plugin-ligo/package.json, taqueria-plugin-smartpy/package.json, taqueria-sdk/index.ts, taqueria-sdk/package.json
As such, the ligo plugin is trying to compile non-ligo source files.
=> SDK's getContracts method not honoring regex pattern

package-lock.json, package.json, taqueria-flextesa-manager/package.json, taqueria-plugin-archetype/package.json, taqueria-plugin-contract-types/package.json, taqueria-plugin-flextesa/package.json, taqueria-plugin-ipfs-pinata/package.json, taqueria-plugin-jest/package.json, taqueria-plugin-ligo/package.json, taqueria-plugin-mock/package.json, taqueria-plugin-smartpy/package.json, taqueria-plugin-taquito/package.json, taqueria-plugin-tezos-client/package.json, taqueria-protocol/package.json, taqueria-sdk/package.json, taqueria-state/package.json, taqueria-vscode-extension/package.json, taqueria-vscode-extension/src/extension.ts, taqueria-vscode-extension/src/lib/gui/ContractsDataProvider.ts, taqueria-vscode-extension/src/lib/gui/EnvironmentsDataProvider.ts, taqueria-vscode-extension/src/lib/gui/PluginsDataProvider.ts, taqueria-vscode-extension/src/lib/gui/SandboxesDataProvider.ts, taqueria-vscode-extension/src/lib/gui/ScaffoldsDataProvider.ts, taqueria-vscode-extension/src/lib/gui/TaqueriaDataProviderBase.ts, taqueria-vscode-extension/src/lib/gui/TestDataProvider.ts, taqueria-vscode-extension/src/lib/helpers.ts, taqueria-vscode-extension/src/lib/pure.ts, tests/package.json
Release PR:
- Includes VSCE Welcome-UX improvements
- Bumps versions for full release
=> Taqueria v0.12.0 release

package-lock.json, taqueria-vscode-extension/package.json, taqueria-vscode-extension/src/lib/helpers.ts
=> Format JSON responses from CLI as Table

taqueria-vscode-extension/src/extension.ts, taqueria-vscode-extension/src/lib/helpers.ts, taqueria-vscode-extension/src/lib/pure.ts
=> avoid calling taq testFromVsCode before all commands

taqueria-vscode-extension/package.json
=> Add generate types command to the GUI

taqueria-vscode-extension/package.json
=> Fix add & remove contract command orders in Contracts tree view

cspell.json, package-lock.json, taqueria-vscode-extension/package.json, taqueria-vscode-extension/src/extension.ts, taqueria-vscode-extension/src/lib/gui/SystemCheckDataProvider.ts, taqueria-vscode-extension/src/lib/helpers.ts, taqueria-vscode-extension/src/lib/pure.ts
=> Add node version check to system health check

taqueria-vscode-extension/src/lib/helpers.ts
=> remove strange characters from jest output

package-lock.json, taqueria-vscode-extension/src/lib/gui/ArtifactsDataProvider.ts, taqueria-vscode-extension/src/lib/helpers.ts
=> fix artifacts treeView for smartpy

taqueria-vscode-extension/src/lib/helpers.ts
=> Fix table formatting, remove bad characters for WSL

taqueria-vscode-extension/package.json, taqueria-vscode-extension/src/lib/helpers.ts
=> Add compile and originate commands to explorer

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/dev_task.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/pull_request_template.md
This PR makes improvements to the Issue templates, and adds a PR template
=> Improved Github Issue Templates and PR Template

tests/e2e/taqueria-plugin-contract-types.spec.ts
- Run test that checks default method is created as expected:
- Example contract:
- https://github.com/ecadlabs/taqueria/blob/1542cda9768ef90ffc21888dfa80a541f7701e6f/taqueria-plugin-contract-types/example/contracts/example-contract-10.tz#L1
- Result type with default:
- https://github.com/ecadlabs/taqueria/blob/1542cda9768ef90ffc21888dfa80a541f7701e6f/taqueria-plugin-contract-types/example/types-file/example-contract-10.types.ts#L9
=> Verify default method is generated (Add test)

taqueria-plugin-ligo/compile.ts, taqueria-plugin-ligo/index.ts, tests/e2e/data/help-contents/ligo-contents.ts, tests/e2e/taqueria-cli-permissions.spec.ts, tests/e2e/taqueria-plugin-contract-types.spec.ts, tests/e2e/taqueria-plugin-ligo.spec.ts, tests/package.json
=> 🏗️ PR ➾ Fix lig-plugin and cli-permission tests

.github/workflows/main.yml, .github/workflows/npm-publish.yml, package-lock.json, package.json, taqueria-flextesa-manager/package.json, taqueria-plugin-archetype/package.json, taqueria-plugin-contract-types/package.json, taqueria-plugin-flextesa/package.json, taqueria-plugin-ipfs-pinata/package.json, taqueria-plugin-jest/package.json, taqueria-plugin-ligo/package.json, taqueria-plugin-metadata/package-lock.json, taqueria-plugin-metadata/package.json, taqueria-plugin-mock/package.json, taqueria-plugin-smartpy/package.json, taqueria-plugin-taquito/package.json, taqueria-plugin-tezos-client/package.json, taqueria-protocol/package.json, taqueria-sdk/package.json, taqueria-state/package.json, taqueria-vscode-extension/package.json, tests/package.json
These changes were part of the final release v0.14.4
=> Final release 0.14.4

taqueria-plugin-flextesa/proxy.ts, taqueria-plugin-tezos-client/client.ts, tests/e2e/taqueria-plugin-flextesa.spec.ts, tests/e2e/taqueria-plugin-taquito-flextesa.spec.ts, tests/e2e/utils/utils.ts, tests/package.json
=> Fix failing tests after TVsCE feature merge

taqueria-vscode-extension/src/lib/helpers.ts
=> Update originate command to select contract file

package-lock.json, package.json, taqueria-flextesa-manager/package.json, taqueria-plugin-archetype/package.json, taqueria-plugin-contract-types/package.json, taqueria-plugin-flextesa/package.json, taqueria-plugin-ipfs-pinata/package.json, taqueria-plugin-jest/package.json, taqueria-plugin-ligo/package.json, taqueria-plugin-metadata/package-lock.json, taqueria-plugin-metadata/package.json, taqueria-plugin-mock/package.json, taqueria-plugin-smartpy/package.json, taqueria-plugin-taquito/package.json, taqueria-plugin-tezos-client/package.json, taqueria-protocol/package.json, taqueria-sdk/package.json, taqueria-state/package.json, taqueria-toolkit/package.json, taqueria-vscode-extension/package.json, tests/package.json, website/docs/getting-started/installation.mdx
=> release v0.18.0

tests/e2e/taqueria-plugin-taquito.spec.ts, website/docs/scaffolds/nft-scaffold.mdx, website/docs/scaffolds/quickstart.mdx, website/docs/scaffolds/scaffold-basics.mdx, website/docs/scaffolds/taco-shop.mdx
=> Adding links to scaffold projects in the table

cspell.json, taqueria-vscode-extension/src/lib/helpers.ts
=> add mock and metadata plugins

website/docs/scaffolds/taco-shop.mdx
=> updating quickstart section and a few other places

taqueria-vscode-extension/package.json, taqueria-vscode-extension/src/extension.ts, taqueria-vscode-extension/src/lib/SmartContractLanguageInfo.ts, taqueria-vscode-extension/src/lib/gui/ArtifactsDataProvider.ts, taqueria-vscode-extension/src/lib/gui/ContractsDataProvider.ts, taqueria-vscode-extension/src/lib/helpers.ts
=> Fix originate and compile commands in command pallet

package-lock.json, package.json, taqueria-flextesa-manager/package.json, taqueria-plugin-archetype/package.json, taqueria-plugin-contract-types/package.json, taqueria-plugin-flextesa/package.json, taqueria-plugin-ipfs-pinata/package.json, taqueria-plugin-jest/package.json, taqueria-plugin-ligo/package.json, taqueria-plugin-metadata/package-lock.json, taqueria-plugin-metadata/package.json, taqueria-plugin-mock/package.json, taqueria-plugin-smartpy/package.json, taqueria-plugin-taquito/README.md, taqueria-plugin-taquito/_readme.eta, taqueria-plugin-taquito/package.json, taqueria-plugin-tezos-client/package.json, taqueria-protocol/package.json, taqueria-sdk/package.json, taqueria-state/package.json, taqueria-toolkit/package.json, taqueria-vscode-extension/package.json, tests/package.json, website/docs/getting-started/installation.mdx, website/docs/release-notes.mdx, website/docusaurus.config.js
This PR bumps the versions of taqueria packages to 0.20.2 to match the release, which went out on an unmerged branch. It also updates reference to the current taqueria version in the docs to be 0.20.2
None
=> 🏗️ PR ➾ Update package versions for 0.20.2 release

.github/ISSUE_TEMPLATE/dev_task.yml, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
=> Houston improve templates

tests/e2e/taqueria-cli-other-and-mixed-plugin-commands.spec.ts
Please include a summary of the changes to the codebase. Please also include relevant motivation and context for the change
Please describe the testing strategy and plan for this PR
=> updated test to now accept main as a taqueria build version

taqueria-vscode-extension/src/lib/helpers.ts
Please include a summary of the changes to the codebase. Please also include relevant motivation and context for the change
Please describe the testing strategy and plan for this PR
Closes #1349
=> remove deprecated scaffolds

taqueria-config.ts, tests/e2e/taqueria-plugin-jest.spec.ts, website/docs/config/environments.mdx, website/docs/config/implicit-accounts.mdx, website/docs/config/networks.mdx, website/docs/config/sandbox-config.mdx, website/docs/release-notes.mdx, website/docs/scaffolds/taco-shop.mdx
Reverts ecadlabs/taqueria#1316
=> Revert "Add ghostnet as a pre-configured testnet"

.github/workflows/main.yml
The publish job should not require that tests pass because by the time the packages are published, the tests should already be passing
=> fix(ci): changed publish job to need build-and-cache-node-modules

taqueria-plugin-ligo/common.ts, taqueria-plugin-ligo/compile.ts, taqueria-plugin-ligo/ligo.ts, taqueria-plugin-ligo/test.ts, taqueria-plugin-tezos-client/client.ts, taqueria-plugin-tezos-client/common.ts, taqueria-plugin-tezos-client/simulate.ts, taqueria-plugin-tezos-client/typecheck.ts
Made a change in the LIGO plugin to point to the most recent stable version of LIGO docker image (but not using the `latest` nor `stable` tag).
Please describe the testing strategy and plan for this PR
=> Change ligo from next to stable version

taqueria-vscode-extension/src/lib/helpers.ts, taqueria-vscode-extension/src/lib/pure.ts
_Please describe the testing strategy and plan for this PR_
=> fix taq installation detection

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/dev_task.yml, .github/pull_request_template.md
Minor fixes to templates based on feedback from the team
=> 👷 Refactor ➾ Improve Issue and PR Templates

website/docs/release-notes.mdx
Super tiny fix for an incorrect version number in the release notes
=> 🛠️ Fix ➾ Update Current Version in Release Notes to v0.22.2

.github/workflows/main.yml, taqueria-vscode-extension/package.json, taqueria-vscode-extension/src/lib/GeneralHelperFunctions.ts, taqueria-vscode-extension/src/lib/helpers.ts
=> Fix typecheck command in the VsCode Extension

website/docs/release-notes.mdx
Add instructions for users to install the Taqueria v0.22.2 binary 
N/A
=> 🛠️ Fix ➾ Add instructions for Updating `taq` Binary to Release Notes

.github/ISSUE_TEMPLATE/bug_report.yml
This tiny PR removes Ivan as the default assignee for bug report tickets and sets Alex as the new default assignee 
=> 🧽 Chore ➾ Update Default Assignee on Bug Report Template to `alexzbusko` from `sinapsist`

taqueria-flextesa-manager/Dockerfile, taqueria-flextesa-manager/lib.ts, taqueria-plugin-flextesa/proxy.ts, taqueria-plugin-tezos-client/simulate.ts, taqueria-plugin-tezos-client/typecheck.ts, taqueria-sdk/index.ts, tests/e2e/taqueria-plugin-taquito-flextesa.spec.ts
The binary name has changed from `tezos-client` to `octez-client`, so we have to adjust our plugins accordingly.
=> 🛠️ Fix ➾ Use `octez-client` instead of `tezos-client` in new Flextesa image version in our plugins

taqueria-flextesa-manager/lib.ts, taqueria-plugin-flextesa/tzkt-manager.ts
=> Update tzkt to match flextesa

.github/ISSUE_TEMPLATE/dev_task.yml
This PR adds the missing work description field back into the dev-task issue template
Merge in and test in production
=> 🧽 Chore ➾ Add the Work Description Field Back into the `dev-task` Issue Template

tests/e2e/data/empty-jest-test-file-1.ts, tests/e2e/data/empty-jest-test-file-2.ts
=> Updating tests to become modules for TS requirement

.github/workflows/add-pr-to-scrum-board.yml
Fixes an issue where PR's marked `ready for review` are not being added to the dev board
Merge in and test live
=> 🛠️ Fix ➾ Remove `name` Field from `add-to-project` Action

taqueria-plugin-ligo/README.md, taqueria-plugin-ligo/_readme.eta, taqueria-plugin-ligo/compile.ts, taqueria-plugin-ligo/index.ts, tests/e2e/data/help-contents/ligo-contents.ts, website/docs/getting-started/quickstart.mdx, website/docs/scaffolds/taco-shop.mdx
Reverts ecadlabs/taqueria#1507
=> Revert "✨ Feature ➾ Rename `<CONTRACT>.storages.mligo` to `<CONTRACT>.storageList.mligo` and similarly for the parameter part"

.github/workflows/add-pr-to-scrum-board.yml
Reverts ecadlabs/taqueria#1516
=> Revert "🛠️ Fix ➾ Remove `name` Field from `add-to-project` Action"

taqueria-plugin-ligo/README.md, taqueria-plugin-ligo/_readme.eta, taqueria-plugin-ligo/compile.ts, taqueria-plugin-ligo/index.ts, tests/e2e/data/help-contents/ligo-contents.ts, website/docs/getting-started/quickstart.mdx, website/docs/scaffolds/taco-shop.mdx
Reverts ecadlabs/taqueria#1520
=> Revert "Revert "✨ Feature ➾ Rename `<CONTRACT>.storages.mligo` to `<CONTRACT>.storageList.mligo` and similarly for the parameter part""

tests/e2e/taqueria-cli-scaffolding-functional.spec.ts
Update e2e test in Taqueria repo to reflect this: https://github.com/ecadlabs/taqueria-scaffold-taco-shop/commit/8733d6587896a03ce88a29aaa6ff71186f5deeb5
=> 🛠️ Fix ➾ Update e2e test to reflect taco shop scaffold repo change

tests/e2e/taqueria-plugin-flextesa.spec.ts
=> Skip one test

tests/e2e/taqueria-plugin-taquito-flextesa.spec.ts
=> Do not check for stopped container in e2e test

README.md
Close #1528 
now the main readme has info in the test section, and prospective users do not have to search for it internally.
- [x ] ⛱️ I have completed this PR template in full and updated the title appropriately
- [x ] ⛵ My code builds cleanly, and I have manually tested the changes
added the content of the test dir readme to the main readme, at the and
Read the docs and review the layout etc, and content
=> To clarify for new users how to run the tests, surface test readme to main readme

tests/README.md
=> Updated test readme to reflect build process

bin/before-all-tests.sh, bin/build-all.sh, taqueria-plugin-flextesa/proxy.ts, tests/e2e/taqueria-cli-scaffolding-functional.spec.ts
Some tests are failing most of the time on Mac Minis but not Linuxes
=> 🛠️ Fix ➾ Clean all docker containers before running any tests

.github/workflows/main.yml, bin/build-all.sh, bin/set-vars.sh
In a previous PR, we added a dependency check before build and test. This improves the output to be more user-friendly and descriptive.
Also, removed dependency of tests in CI on build-binary, so that they start faster (and end faster).
=> Improve output when checking Dependencies, Remove dependency of tests step on build-binaries

taqueria-plugin-ligo/compile.ts, tests/jest.config.unit.ts, tests/unit/ligo-plugin-tests/ligo-plugin-tests.spec.ts
Adding unit tests for the ligo plugin, starting with compile
=> Mk 1578 ligo plugin unit tests

README.md
When a user checks out the taqueria project, builds, and tries to run tests, but had a previous taq version installed, they could run into trouble.
I've added a note that might help users determine whether taq is installed properly, and to help them verify which version of taq they are running.
=> 🛠️ Fix ➾ Added instructions to help users verify that they have taq installed

README.md
Remove redundant warning in the README.md
=> Remove redundant warning

tests/e2e/taqueria-plugin-taquito.spec.ts
the test has to be run twice to pass and is hampering cicd flow
mark the test skip with a remark pointing to the issue in github
fix the flakiness eventually but for now quarantine
cicd should not require rerunning a job
- [x ] 🛠️ Fix ➾
=> mark the Taquito plugin  transfer tez test as flaky

taqueria-plugin-flextesa/tzkt-manager.ts
Because of some new changes in Flextesa, TzKt.Sync fails to work
- Because TzKt has been updated to .net 7, our .net 6 branch was no longer needed
- Created a clean branch from upstream and applied the required changes:
- Accept Protocol Alpha
- Allow overriding the number of attempts for database migrations in TzKt.Api
- Logged two issues in TzKt repo to ask for these changes in upstream:
- [Accept protocol Alpha](https://github.com/baking-bad/tzkt/issues/138)
- [Allow overriding the number of attempts in TzKt.Ap](https://github.com/baking-bad/tzkt/issues/137)
- Created a pull request to upstream that fixes the two feature requests
- Tested the change locally
- Created a draft PR (this one)
- We should either:
-  wait for Baking bad to merge our PR, and change our code to use their image …
=> Fix Failure in TzKt.Sync

package-lock.json, tests/e2e/taqueria-cli-e2e-smoke.spec.ts, tests/e2e/taqueria-plugin-contract-types.spec.ts, tests/e2e/taqueria-plugin-ligo.spec.ts, tests/e2e/taqueria-plugin-taquito.spec.ts, tests/integration/taqueria-cli-permissions.spec.ts, tests/integration/taqueria-cli-scaffolding-functional.spec.ts, tests/integration/taqueria-plugin-taquito-integration.spec.ts, tests/jest.config.integration.ts, tests/package.json
cleanup and organization of some E2E tests
close #1708 
cleanup and organization of some E2E tests
-moved a couple of flaky Taquito plugin tests to integration
-unskip contextual help tets that work now
- general cleanup where needed
- drop a couple of tests that are effectively meaningless or redundant
test working in cicd and in local
=> cleanup and organization of some E2E tests

README.md, package-lock.json, tests/README.md, tests/tsconfig.test.json
Revise test readme and remove some unneeded ts.config
Revise test readme and remove some unneeded ts.config
tests should keep working
text should be clearer
- [z ] 🧽 Chore ➾
=> revise test readme and remove some unneeded ts.config

tests/e2e/taqueria-workflows.spec.ts
added workflow tests
- [x ] ⛱️ I have completed this PR template in full and updated the title appropriately
added workflow tests
tests work
- [x ] 🧽 Chore ➾
=> added workflow tests

README.md, tests/README.md
Running the unit tests requires deno is installed on your system. Installation instructions can be found [here](https://deno.land/manual@v1.18.2/getting_started/installation)
If you are running from built sources, start with `npm run build-all`
- The tests should be run from the taqueria root folder by calling the test run script with the workspace specified: `npm run test:{unit|integration|e2e} -w tests`
- the package.json file in the /tests directory lists various combinations of tests that can be invoked from the command line.
see above
should read ok and links should work
- [x ] 🧽 Chore ➾
=> revised the tests readmes

tests/e2e/archetype-plugin-e2e-tests.spec.ts, tests/e2e/cli-e2e-smoke-tests.spec.ts, tests/e2e/cli-persistent-state-e2e-tests.spec.ts, tests/e2e/contract-types-plugin-e2e-tests.spec.ts, tests/e2e/ligo-plugin-e2e-tests.spec.ts
closes #1760
extend coverage for  e2e tests for plugin cli options
- [x ] ⛱️ I have completed this PR template in full and updated the title appropriately
- [x ] ⛵ My code builds cleanly, and I have manually tested the changes
- [x ] 🏖️ New and existing unit tests pass locally and in CI
- [x ] 🦀 Automated tests have been written and added to this PR
- [x ] 🐬 I have commented my code, particularly in hard-to-understand areas
- [x ] 🤿 Corresponding changes have been made to all documentation
- [x ] 🐚 Required changes to the VScE have been made
- [x ] 🪸 Required updates to scaffolds have been made
extend coverage for  e2e tests for plugin cli options
tests keep working
=> extend coverage for  e2e tests for plugin cli options

website/docusaurus.config.js
Fixes the incorrect version number on the Taqueria.io homepage 
Manually verify
=> 🛠️ Fix ➾ Fix Incorrect Version Number on Taqueria Homepage

taqueria-protocol/types-config-files.ts
A debugger statement was unintentionally committed to the repo.
Removed the unintended `debugger;` statement.
=> Remove unwanted debugger statement

taqueria-plugin-contract-types/tasks.ts, taqueria-plugin-tezos-client/common.ts, taqueria-plugin-tezos-client/index.ts, taqueria-plugin-tezos-client/main.ts, taqueria-plugin-tezos-client/typecheck.ts, taqueria-plugin-tezos-client/typecheckAll.ts, taqueria-sdk/index.ts, tests/e2e/tezos-client-plugin-e2e-tests.spec.ts
Fixes #1671
`taq typecheck-all` will type check all Michelson contracts under `artifacts/`
=> ✨ Feature ➾ Implement typecheck-all

website/docs/config/config-files.mdx, website/docs/config/environments.mdx
Add back instructions on how to deploy to mainnet to the website and fixed a link issue in the website.
=> 🛠️ Fix ➾ Add back instructions on how to deploy to mainnet to the website

tests/e2e/contract-types-plugin-e2e-tests.spec.ts
one contextual help fix needed an additional fix
- [ x] ⛱️ I have completed this PR template in full and updated the title appropriately
fix for contextual help test
working test
- [x ] 🧽 Chore ➾
=> fix for contextual help test

bin/build.sh, bin/debug.sh, bin/run.sh, cli.ts
The output of the help menu is now dynamically set to the number of columns of your TTY.
=> 🛠️ Fix ➾ Dynamically set the column wrapping of the yargs help menu

lerna.json, package-lock.json, package.json, taqueria-analytics/package.json, taqueria-plugin-archetype/package.json, taqueria-plugin-contract-types/package.json, taqueria-plugin-core/package.json, taqueria-plugin-flextesa/package.json, taqueria-plugin-ipfs-pinata/package.json, taqueria-plugin-jest/package.json, taqueria-plugin-ligo/package.json, taqueria-plugin-metadata/package.json, taqueria-plugin-smartpy/package.json, taqueria-plugin-taquito/package.json, taqueria-plugin-tezos-client/package.json, taqueria-sdk/package.json, taqueria-vscode-extension/package.json
Includes:
- Fixes to the @taqueria/protocol package ensuring that it can be consumed in Node.js, Deno, and Browser runtimes
- Fixes to the @taqueria/toolkit package to ensure that Base64 encoding is handled properly
- Uninstall task does not fail
- Yes to all works as it should
=> 🧪 Pre-Release ➾ v0.28.1 (and VSCode v0.29.0)

lerna.json, package-lock.json, package.json, taqueria-analytics/package.json, taqueria-plugin-archetype/package.json, taqueria-plugin-contract-types/package.json, taqueria-plugin-core/package.json, taqueria-plugin-flextesa/package.json, taqueria-plugin-ipfs-pinata/package.json, taqueria-plugin-jest/package.json, taqueria-plugin-ligo/package.json, taqueria-plugin-metadata/package.json, taqueria-plugin-smartpy/package.json, taqueria-plugin-taquito/package.json, taqueria-plugin-tezos-client/package.json, taqueria-protocol/package.json, taqueria-sdk/package.json, taqueria-toolkit/package.json, taqueria-vscode-extension/package.json, website/docs/release-notes.mdx
=> 🚀 Release ➾ v0.28.2

taqueria-plugin-ligo/ligo.ts, tests/e2e/ligo-plugin-e2e-tests.spec.ts
=> 🛠️ Fix ➾ Ensure that files created by ligo/docker aren't owned by root

taqueria-plugin-ligo/ligo.ts
Fixes #1851, `ligo` command not working.
=> 🛠️ Fix ➾ Bug with user mapping when invoking ligo plugin

lerna.json, package-lock.json, package.json, taqueria-analytics/package.json, taqueria-plugin-archetype/package.json, taqueria-plugin-contract-types/package.json, taqueria-plugin-core/package.json, taqueria-plugin-flextesa/package.json, taqueria-plugin-ipfs-pinata/package.json, taqueria-plugin-jest/package.json, taqueria-plugin-ligo/package.json, taqueria-plugin-metadata/package.json, taqueria-plugin-smartpy/package.json, taqueria-plugin-taquito/package.json, taqueria-plugin-tezos-client/package.json, taqueria-protocol/package.json, taqueria-sdk/package.json, taqueria-toolkit/package.json, taqueria-vscode-extension/package.json, website/docs/release-notes.mdx
- Support the latest protocols (Mumbai)
- Update all third-party tools to their latest versions, aside from SmartPy which needs a closer look.
- Closes #1857
- Closes #1854.
=> 🧪 Pre-Release ➾ v0.28.5

taqueria-plugin-ligo/ligo.ts, tests/e2e/ligo-plugin-e2e-tests.spec.ts, tests/e2e/ligo-regression-e2e-test.spec.ts
LIGO uses package.json by default to manage dependencies. However, that conflicts with Taqueria. However, if an esy.json file exists then LIGO will use that instead.
This PR will check if esy.json file exists prior to dispatching to the LIGO CLI when the `taq ligo` task is executed, and if not, will create one so that the `taq ligo --command install` command will work without error.
- [x ] ⛱️ I have completed this PR template in full and updated the title appropriately
- [x ] ⛵ My code builds cleanly, and I have manually tested the changes
- [x ] 🦀 Automated tests have been written and added to this PR
- [x ] 🐬 I have commented my code, particularly in hard-to-understand areas
- Adjust the `ligo` task provided by our ligo plugin to create an esy.json file in the root …
=> 🛠️ Fix ➾ Ensure that `taq ligo --command install` works by creating esy.json file

website/docs/getting-started/quickstart.mdx
=> 🛠️ Fix ➾ Removed caution about init task that was no longer relevant on quickstart page

taqueria-plugin-tezos-client/common.ts, taqueria-vscode-extension/README.md, tests/e2e/contract-types-plugin-e2e-tests.spec.ts, tests/e2e/data/config-data/config-default-environment-testing.json, tests/e2e/data/config-data/config-flextesa-test-sandbox.json, tests/e2e/data/config-data/config-no-sandboxes.json, tests/e2e/data/config-data/config-taquito-test-environment-funded-pkh.json, tests/e2e/data/config-data/config-taquito-test-environment-invalid-config-networkname.json, tests/e2e/data/config-data/config-taquito-test-environment-invalid-initial-storage-string.json, tests/e2e/data/config-data/config-taquito-test-environment-low-tez.json, tests/e2e/data/config-data/config-taquito-test-environment.json, tests/e2e/data/config-data/config-without-default-environment.json, tests/e2e/ligo-plugin-e2e-tests.spec.ts, tests/e2e/marigold-training-e2e-smoke-test.spec.ts, tests/e2e/taquito-plugin-e2e-tests.spec.ts, tests/integration/various-flaky-plugin-integration-tests.spec.ts, tests/unit/taqueria-sdk/data/runtime/config.json, tests/unit/taqueria-sdk/data/v1/.taq/config.json, tests/unit/taqueria-sdk/data/v2/.taq/config.json
Updates the README file for the VSCode extension to mention that Taqueria v0.28.6 is required.
=> 🧽 Chore ➾ Updated Taqueria version in readme.txt

taqueria-plugin-ligo/ligo_templates.ts
A new simpler way to manage entrypoint in ligo through annotation exist. It's better for user experience
Todo
Todo
=> Draft: Update ligo_templates.ts with entry annotation
